Warning: cannot import name 'logsumexp' from 'scipy.misc' (/home/sabrinab/miniconda3/envs/PyPlanet/lib/python3.9/site-packages/scipy/misc/__init__.py). For full functionality of BurnMan, please install cvxpy.
Warning: No module named 'cdd'. For full functionality of BurnMan, please install pycddlib.
Warning: cannot import name 'logsumexp' from 'scipy.misc' (/home/sabrinab/miniconda3/envs/PyPlanet/lib/python3.9/site-packages/scipy/misc/__init__.py). For full functionality of BurnMan, please install cvxpy.
Traceback (most recent call last):
  File "/scratch/sabrinab/PyPlanet/run_test.py", line 109, in <module>
    varying_temp("_adiabatic_", temp_range, default_central_pressures, default_grid_size, thermal_location, testing)
  File "/scratch/sabrinab/PyPlanet/run_test.py", line 86, in varying_temp
    temp_plan_grid = PlanetGrid(temp, central_pressures, grid_size, str(type_eos), loc, layers_types=layers_normal,
  File "/scratch/sabrinab/PyPlanet/planet_grid.py", line 40, in __init__
    [10 ** x for x in linspace(self.central_pressures[0], self.central_pressures[1], self.grid_size[0])])
IndexError: list index out of range
